Iter13
DieOfCode/go-alert-service pull request #22
Opened 2024-02-13 20:57 UTC by DieOfCode

2024-02-16 01:21 UTC, Nikscorp requested changes
Оставил замечания в ишью к PR

2024-02-16 01:21 UTC, Nikscorp commented on internal/storage/db_storage.go
> +func (storage *DatabaseStorage) LoadAll() metrics.Data {
1. Не принимается контекст, во все io операции должен прокдываться контекст
2. Не возвращается ошибка, а должна возвращаться и врапаться

2024-02-16 01:21 UTC, Nikscorp commented on internal/storage/db_storage.go
> +func (storage *DatabaseStorage) LoadAll() metrics.Data {
актуально для всех методов данного пакета

2024-02-16 01:21 UTC, Nikscorp commented on internal/storage/db_storage.go
> +		stored = storage.Store(metric)
получается никакого смысла в матчах нет)

по-хорошему
нужно или сразу инсертить несколько значений, предварительно разбивая на более маленькие пачки или bulk insert делать. Ну или как минимум транзакционность сделать.

Это все не совсем тривиально, так что если не успеешь — можешь пока оставить

2024-02-16 01:21 UTC, Nikscorp commented on internal/storage/db_storage.go
> +			"UPDATE metrics SET delta = $1 WHERE id = $2 AND type = $3",
можно делать за один запрос используя https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT

2024-02-16 01:21 UTC, Nikscorp commented on internal/storage/db_storage.go
> +		affected, err := result.RowsAffected()
вот на это забей, не всегда драйверы этот rowsAffected корректно заполняют

2024-02-16 01:21 UTC, Nikscorp commented on internal/storage/db_storage.go
> +func (storage *DatabaseStorage) Store(m metrics.Metric) bool {
метод выглядит сложночитаемо, лучше разбить на более мелкие приватные

2024-02-16 01:21 UTC, Nikscorp commented on internal/agent/agent.go
> +func (a *Agent) Retry(ctx context.Context, maxRetries int, fn func(ctx context.Context) error, intervals ...time.Duration) error {
нуу ты сильно урезал задание по факту, нет ретраев для БД, а для клиента нет обработки retriable ошибок.

Но допустим ок и пока можно оставить

2024-02-21 10:23 UTC, DieOfCode commented on internal/storage/db_storage.go
> +		stored = storage.Store(metric)
Не успел это сделать, закрою на след спринте

2024-02-22 01:42 UTC, Nikscorp commented on cmd/server/main.go
> +		if err := db.Ping(); err != nil {
не исправлено

2024-02-22 01:43 UTC, Nikscorp commented on cmd/server/main.go
> +			print("proble getting instance")
не испралвено, в коде еще остались print-ы

2024-02-22 01:45 UTC, Nikscorp commented on internal/agent/agent.go
> +		a.logger.Error().Err(err).Msg("Marshalling error")
не исправлено

2024-02-22 01:46 UTC, Nikscorp commented on internal/storage/db_storage.go
> +func (storage *DatabaseStorage) LoadAll() metrics.Data {
не исправлено

2024-02-22 01:46 UTC, Nikscorp commented on internal/storage/db_storage.go
> +		stored = storage.Store(metric)
ок

2024-02-22 01:51 UTC, Nikscorp commented on internal/agent/agent.go
> +func (a *Agent) Retry(ctx context.Context, maxRetries int, fn func(ctx context.Context) error, intervals ...time.Duration) error {
тоже не исправлено, но

> Но допустим ок и пока можно оставить

2024-02-22 01:52 UTC, Nikscorp requested changes
указал в комментариях те ишью, которые ты пропусти

Самое важное — пробросим контекста из реквеста и обработка ошибок

2024-02-25 09:43 UTC, DieOfCode commented on cmd/server/main.go
> +		if err := db.Ping(); err != nil {
Возможно не совсем понял , что тут надо сделать, пробросил контекст в логирование ошибки об отсутствии БД

2024-02-27 08:58 UTC, Nikscorp requested changes

2024-02-27 08:58 UTC, Nikscorp commented on internal/storage/db_storage.go
> +func (storage *DatabaseStorage) LoadAll() metrics.Data {
Я не понимаю почему это до сих пор не исправлено, это основное замечание ко всей работе.

Если ты оставляешь какие-то комментарии — их не видно, тк ты их не паблишишь.

Еще раз:
- работа с контекстом это одна из основных тем спринта
- контекст http реквеста нужно передавать в нижележащие слои, в том числе в слой storage, чтобы при сценарии отмены http реквеста ты не производил бесполезные вычисления БД. Все методы работы с БД перевести с Query -> QueryContext (аналогично для Exec)

2024-02-27 08:58 UTC, Nikscorp commented on internal/agent/agent.go
> +		a.logger.Error().Err(err).Msg("Marshalling error")
все еще не исправлено

2024-02-27 09:01 UTC, Nikscorp commented on internal/agent/agent.go
> +				a.logger.Error().Err(err).Msg("clieчаnt.Do method error")
clieчаnt

2024-04-22 22:42 UTC, closed without merging